name: CI
on: [push, pull_request]

jobs:
  test_and_lint:
    name: Test and lint
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: conda install libopencv opencv=4.5.1 py-opencv -c conda-forge
    - name: Install package with test dependencies
      run: pip install .[tests]
    - name: Run PyTest
      run: pytest
      env:
         PYTHONHASHSEED: '0'
    - name: Run Flake8
      run: flake8
    - name: Run mypy
      run: mypy .
    - name: Run Black
      run: black --check .
    - name: Run isort
      run: isort --check-only