name: CI
on: [push, pull_request]

jobs:
  test_and_lint:
    name: Test and lint
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: pip install .[tests]
    - name: Install linters
      run: pip install flake8 mypy black
    - name: Run PyTest
      run: pytest
    - name: Run Flake8
      run: flake8
    - name: Run mypy
      run: mypy .
    - name: Run Black
      run: black --check .

  # check_sphinx_build:
  #   name: Check Sphinx build for docs
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: [3.8]
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Update pip
  #     run: python -m pip install --upgrade pip
  #   - name: Install dependencies
  #     run: pip install -r docs/requirements.txt
  #   - name: Run Sphinx
  #     run: sphinx-build -b html docs /tmp/_docs_build

